<a href="https://colab.research.google.com/github/yash5891/Machine-Learning-Assignments/blob/main/linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np
import pandas as pd


In [ ]:
df=pd.read_csv("/content/train.csv")

In [ ]:
df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1460 non-null   int64  
 1   MSSubClass     1460 non-null   int64  
 2   MSZoning       1460 non-null   object 
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64  
 5   Street         1460 non-null   object 
 6   Alley          91 non-null     object 
 7   LotShape       1460 non-null   object 
 8   LandContour    1460 non-null   object 
 9   Utilities      1460 non-null   object 
 10  LotConfig      1460 non-null   object 
 11  LandSlope      1460 non-null   object 
 12  Neighborhood   1460 non-null   object 
 13  Condition1     1460 non-null   object 
 14  Condition2     1460 non-null   object 
 15  BldgType       1460 non-null   object 
 16  HouseStyle     1460 non-null   object 
 17  OverallQual    1460 non-null   int64  
 18  OverallC

In [ ]:
df.isnull().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ... 
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [ ]:
df.shape

(1460, 81)

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

In [ ]:
# prompt: do label encoding for object columns

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for col in df.select_dtypes(include='object'):
    df[col] = le.fit_transform(df[col])


In [ ]:

df.describe()
df.info()


<class 'pandas.core.frame.DataFrame'>
Index: 1121 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             1121 non-null   int64  
 1   MSSubClass     1121 non-null   int64  
 2   MSZoning       1121 non-null   int64  
 3   LotFrontage    1121 non-null   float64
 4   LotArea        1121 non-null   int64  
 5   Street         1121 non-null   int64  
 6   Alley          1121 non-null   int64  
 7   LotShape       1121 non-null   int64  
 8   LandContour    1121 non-null   int64  
 9   Utilities      1121 non-null   int64  
 10  LotConfig      1121 non-null   int64  
 11  LandSlope      1121 non-null   int64  
 12  Neighborhood   1121 non-null   int64  
 13  Condition1     1121 non-null   int64  
 14  Condition2     1121 non-null   int64  
 15  BldgType       1121 non-null   int64  
 16  HouseStyle     1121 non-null   int64  
 17  OverallQual    1121 non-null   int64  
 18  OverallCond  

In [ ]:
# prompt: do feature selection

from sklearn.feature_selection import SelectKBest, chi2

X = df.drop('SalePrice', axis=1)
y = df['SalePrice']

selector = SelectKBest(chi2, k=10)
X_new = selector.fit_transform(X, y)

print(X_new.shape)


(1121, 10)


In [ ]:
# prompt: drop the columns which contain nan values

df = df.dropna()
df


In [ ]:
# prompt: convert data frame to numpy array

X_new = X.to_numpy()
X_new

array([[1.000e+00, 6.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00],
       [2.000e+00, 2.000e+01, 3.000e+00, ..., 2.007e+03, 8.000e+00,
        4.000e+00],
       [3.000e+00, 6.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00],
       ...,
       [1.458e+03, 7.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.459e+03, 2.000e+01, 3.000e+00, ..., 2.010e+03, 8.000e+00,
        4.000e+00],
       [1.460e+03, 2.000e+01, 3.000e+00, ..., 2.008e+03, 8.000e+00,
        4.000e+00]])

In [ ]:
inputs = torch.from_numpy(X_new)
targets = torch.from_numpy(y.to_numpy())
targets.shape

torch.Size([1121])

In [ ]:
inputs
# inputs = inputs.f

tensor([[1.0000e+00, 6.0000e+01, 3.0000e+00,  ..., 2.0080e+03, 8.0000e+00,
         4.0000e+00],
        [2.0000e+00, 2.0000e+01, 3.0000e+00,  ..., 2.0070e+03, 8.0000e+00,
         4.0000e+00],
        [3.0000e+00, 6.0000e+01, 3.0000e+00,  ..., 2.0080e+03, 8.0000e+00,
         4.0000e+00],
        ...,
        [1.4580e+03, 7.0000e+01, 3.0000e+00,  ..., 2.0100e+03, 8.0000e+00,
         4.0000e+00],
        [1.4590e+03, 2.0000e+01, 3.0000e+00,  ..., 2.0100e+03, 8.0000e+00,
         4.0000e+00],
        [1.4600e+03, 2.0000e+01, 3.0000e+00,  ..., 2.0080e+03, 8.0000e+00,
         4.0000e+00]], dtype=torch.float64)

In [ ]:
targets

tensor([208500, 181500, 223500,  ..., 266500, 142125, 147500])

In [ ]:
# prompt: how many tensor column do input hav


In [ ]:
w = torch.randn(1,80, requires_grad= True,dtype=torch.float)
b = torch.randn(1, requires_grad= True,dtype=torch.float)


In [ ]:
w=w.double()
b=b.double()

In [ ]:
b.shape

torch.Size([1])

In [ ]:
def model(x):
    return x @ w.t() + b

In [ ]:
preds=model(inputs)

In [ ]:
preds

tensor([[2377.4071],
        [3306.2923],
        [2672.9892],
        ...,
        [7513.7333],
        [1974.7660],
        [2797.1494]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [ ]:
def mse(t1, t2):
  diff = t1 - t2
  return torch.sum((diff**2))/ diff.numel()

In [ ]:
loss = mse(preds, targets)
print(loss)

tensor(4.0414e+10, dtype=torch.float64, grad_fn=<DivBackward0>)


In [ ]:
a=loss.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.

In [ ]:
new_var = w.retain_grad()
new_var

In [ ]:
lr = 1e-5
with torch.no_grad():
    w -= w.grad * lr
    b -= b.grad * lr


TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

In [ ]:
from torch import nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader


In [ ]:
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[1.0000e+00, 6.0000e+01, 3.0000e+00, 6.5000e+01, 8.4500e+03, 1.0000e+00,
          2.0000e+00, 3.0000e+00, 3.0000e+00, 0.0000e+00, 4.0000e+00, 0.0000e+00,
          5.0000e+00, 2.0000e+00, 2.0000e+00, 0.0000e+00, 5.0000e+00, 7.0000e+00,
          5.0000e+00, 2.0030e+03, 2.0030e+03, 1.0000e+00, 1.0000e+00, 1.2000e+01,
          1.3000e+01, 1.0000e+00, 1.9600e+02, 2.0000e+00, 4.0000e+00, 2.0000e+00,
          2.0000e+00, 3.0000e+00, 3.0000e+00, 2.0000e+00, 7.0600e+02, 5.0000e+00,
          0.0000e+00, 1.5000e+02, 8.5600e+02, 1.0000e+00, 0.0000e+00, 1.0000e+00,
          4.0000e+00, 8.5600e+02, 8.5400e+02, 0.0000e+00, 1.7100e+03, 1.0000e+00,
          0.0000e+00, 2.0000e+00, 1.0000e+00, 3.0000e+00, 1.0000e+00, 2.0000e+00,
          8.0000e+00, 6.0000e+00, 0.0000e+00, 5.0000e+00, 1.0000e+00, 2.0030e+03,
          1.0000e+00, 2.0000e+00, 5.4800e+02, 4.0000e+00, 4.0000e+00, 2.0000e+00,
          0.0000e+00, 6.1000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
          3.0000

In [ ]:
bs = 5
train_loader = DataLoader(train_ds, batch_size = bs, shuffle = True)

In [ ]:
for xb, yb in train_loader:
    print(xb.double())
    print(yb.double())
    break

tensor([[5.0700e+02, 6.0000e+01, 3.0000e+00, 8.0000e+01, 9.5540e+03, 1.0000e+00,
         2.0000e+00, 0.0000e+00, 3.0000e+00, 0.0000e+00, 4.0000e+00, 0.0000e+00,
         2.0000e+01, 2.0000e+00, 2.0000e+00, 0.0000e+00, 5.0000e+00, 8.0000e+00,
         5.0000e+00, 1.9930e+03, 1.9940e+03, 1.0000e+00, 1.0000e+00, 1.2000e+01,
         1.3000e+01, 1.0000e+00, 1.2500e+02, 2.0000e+00, 4.0000e+00, 2.0000e+00,
         2.0000e+00, 3.0000e+00, 3.0000e+00, 2.0000e+00, 3.8000e+02, 5.0000e+00,
         0.0000e+00, 3.9700e+02, 7.7700e+02, 1.0000e+00, 0.0000e+00, 1.0000e+00,
         4.0000e+00, 1.0650e+03, 8.4600e+02, 0.0000e+00, 1.9110e+03, 0.0000e+00,
         0.0000e+00, 2.0000e+00, 1.0000e+00, 3.0000e+00, 1.0000e+00, 2.0000e+00,
         8.0000e+00, 6.0000e+00, 1.0000e+00, 4.0000e+00, 1.0000e+00, 1.9930e+03,
         1.0000e+00, 2.0000e+00, 4.7100e+02, 4.0000e+00, 4.0000e+00, 2.0000e+00,
         1.8200e+02, 8.1000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         3.0000e+00, 4.0000e

In [ ]:
class Linear_Regression(torch.nn.Module):
     def __init__(self, input_dim, output_dim):
         super(Linear_Regression, self).__init__()
         self.linear = torch.nn.Linear(input_dim, output_dim)
     def forward(self, x):
         outputs = self.linear(x)
         return outputs

In [ ]:
model = Linear_Regression(80,1)

In [ ]:
list(model.parameters())[0][0].dtype

torch.float32

In [ ]:

targets.shape


torch.Size([1121, 1])

In [ ]:
preds = model(inputs.type(torch.float32))
preds

tensor([[ 886.6315],
        [ 942.7352],
        [1089.5115],
        ...,
        [ 969.2125],
        [ 798.3675],
        [ 925.8561]], grad_fn=<AddmmBackward0>)

In [ ]:
(list(model.parameters()))

[Parameter containing:
 tensor([[-0.0121, -0.0083,  0.0235,  0.0660,  0.0835,  0.0272, -0.1069, -0.0715,
          -0.0779,  0.1072, -0.0183, -0.0829,  0.0769, -0.0602, -0.0906, -0.0599,
          -0.0687, -0.0916,  0.0020,  0.0730, -0.0177,  0.0092,  0.1064, -0.0448,
           0.0503,  0.0763,  0.1100, -0.0176, -0.0908, -0.0892, -0.0159, -0.0535,
          -0.0007, -0.0944,  0.0912,  0.0333, -0.0382, -0.0889,  0.0952, -0.0099,
          -0.0707, -0.0143, -0.0498, -0.0165,  0.0262,  0.0366,  0.1037,  0.0256,
          -0.0204,  0.0975,  0.0261,  0.0245, -0.0626,  0.0244, -0.0731,  0.0380,
           0.0326, -0.0164, -0.0409, -0.0412, -0.0214,  0.0275,  0.0329, -0.0101,
          -0.0390,  0.0852, -0.0017, -0.0870,  0.0607, -0.0880, -0.0984,  0.0527,
           0.1032,  0.0671, -0.1115,  0.0367,  0.0986, -0.1005,  0.0650, -0.0043]],
        requires_grad=True),
 Parameter containing:
 tensor([-0.0667], requires_grad=True)]

In [ ]:
import torch.nn.functional as F

In [ ]:
# prompt: convert my target variable shape into same as input variable

targets = targets.view(targets.shape[0], 1)
targets.shape

torch.Size([1121, 1])

In [ ]:
loss_fn = F.mse_loss
loss = loss_fn(model(inputs.type(torch.float32)), targets.type(torch.float32))

print(loss)
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

tensor(nan, grad_fn=<MseLossBackward0>)


In [ ]:
inputs.type(torch.float32)

tensor([[1.0000e+00, 6.0000e+01, 3.0000e+00,  ..., 2.0080e+03, 8.0000e+00,
         4.0000e+00],
        [2.0000e+00, 2.0000e+01, 3.0000e+00,  ..., 2.0070e+03, 8.0000e+00,
         4.0000e+00],
        [3.0000e+00, 6.0000e+01, 3.0000e+00,  ..., 2.0080e+03, 8.0000e+00,
         4.0000e+00],
        ...,
        [1.4580e+03, 7.0000e+01, 3.0000e+00,  ..., 2.0100e+03, 8.0000e+00,
         4.0000e+00],
        [1.4590e+03, 2.0000e+01, 3.0000e+00,  ..., 2.0100e+03, 8.0000e+00,
         4.0000e+00],
        [1.4600e+03, 2.0000e+01, 3.0000e+00,  ..., 2.0080e+03, 8.0000e+00,
         4.0000e+00]])

In [ ]:
# prompt: change my double into float of inputs and targets

inputs = inputs.float()
targets = targets.float()


In [ ]:
# Utility function to train the model
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat for given number of epochs
    for epoch in range(num_epochs):

        # Train with batches of data
        for xb,yb in train_dl:

            # 1. Generate predictions
            pred = model(xb)

            # 2. Calculate loss
            loss_fn = F.mse_loss(pred.unsqueeze(1), yb, reduction='none')

            # 3. Compute gradients


            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

        # Print the progress
        if (epoch+1) % 10 == 0:
            print('Epoch [{}/{}], Loss: {:.4f}'.format(epoch+1, num_epochs, loss.item()))

In [ ]:
fit(100, model, loss_fn, opt, train_loader)


<ipython-input-203-01527d76db33>:14: UserWarning: Using a target size (torch.Size([5])) that is different to the input size (torch.Size([5, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss_fn = F.mse_loss(pred.unsqueeze(1), yb, reduction='none')
<ipython-input-203-01527d76db33>:14: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  loss_fn = F.mse_loss(pred.unsqueeze(1), yb, reduction='none')


Epoch [10/100], Loss: nan
Epoch [20/100], Loss: nan
Epoch [30/100], Loss: nan
Epoch [40/100], Loss: nan
Epoch [50/100], Loss: nan
Epoch [60/100], Loss: nan
Epoch [70/100], Loss: nan
Epoch [80/100], Loss: nan
Epoch [90/100], Loss: nan
Epoch [100/100], Loss: nan


In [ ]:
model(torch.tensor([5.0700e+02, 6.0000e+01, 3.0000e+00, 8.0000e+01, 9.5540e+03, 1.0000e+00,
         2.0000e+00, 0.0000e+00, 3.0000e+00, 0.0000e+00, 4.0000e+00, 0.0000e+00,
         2.0000e+01, 2.0000e+00, 2.0000e+00, 0.0000e+00, 5.0000e+00, 8.0000e+00,
         5.0000e+00, 1.9930e+03, 1.9940e+03, 1.0000e+00, 1.0000e+00, 1.2000e+01,
         1.3000e+01, 1.0000e+00, 1.2500e+02, 2.0000e+00, 4.0000e+00, 2.0000e+00,
         2.0000e+00, 3.0000e+00, 3.0000e+00, 2.0000e+00, 3.8000e+02, 5.0000e+00,
         0.0000e+00, 3.9700e+02, 7.7700e+02, 1.0000e+00, 0.0000e+00, 1.0000e+00,
         4.0000e+00, 1.0650e+03, 8.4600e+02, 0.0000e+00, 1.9110e+03, 0.0000e+00,
         0.0000e+00, 2.0000e+00, 1.0000e+00, 3.0000e+00, 1.0000e+00, 2.0000e+00,
         8.0000e+00, 6.0000e+00, 1.0000e+00, 4.0000e+00, 1.0000e+00, 1.9930e+03,
         1.0000e+00, 2.0000e+00, 4.7100e+02, 4.0000e+00, 4.0000e+00, 2.0000e+00,
         1.8200e+02, 8.1000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         3.0000e+00, 4.0000e+00, 4.0000e+00, 0.0000e+00, 9.0000e+00, 2.0060e+03,
         8.0000e+00, 4.0000e+00]))

tensor([-159.4886], grad_fn=<ViewBackward0>)

In [ ]:
preds = model(inputs)
preds

tensor([[-134.1738],
        [-100.3491],
        [-177.4652],
        ...,
        [-126.8522],
        [-114.5823],
        [ -81.2015]], grad_fn=<AddmmBackward0>)

In [ ]:
# prompt: convert my target data into 2d

targets = targets.reshape(-1,1)
targets.shape()


TypeError: 'torch.Size' object is not callable

In [ ]:
# prompt: convert my target variable data into float

targets = targets.float()
targets.shape()

TypeError: 'torch.Size' object is not callable