<a href="https://colab.research.google.com/github/yash5891/Machine-Learning-Assignments/blob/main/logistic_classification_using_sigmoid.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [56]:
import torch
import numpy as np
import pandas as pd


In [57]:
df=pd.read_csv('/content/creditcard.csv')
df

<ipython-input-57-9b4e49130649>:1: DtypeWarning: Columns (28) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv('/content/creditcard.csv')


Time         V1         V2        V3        V4        V5        V6  \
0           0  -1.359807  -0.072781  2.536347  1.378155 -0.338321  0.462388   
1           0   1.191857   0.266151  0.166480  0.448154  0.060018 -0.082361   
2           1  -1.358354  -1.340163  1.773209  0.379780 -0.503198  1.800499   
3           1  -0.966272  -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4           2  -1.158233   0.877737  1.548718  0.403034 -0.407193  0.095921   
...       ...        ...        ...       ...       ...       ...       ...   
136737  81844 -10.972016 -10.165075  0.579235  1.914312  3.971221 -3.571746   
136738  81844   1.424511  -1.481277  0.827126 -1.263302 -1.806258  0.125942   
136739  81845   1.067404   0.087153  0.100938  0.986393 -0.082482 -0.412316   
136740  81846  -0.833219   0.746826  1.747488 -0.016827 -0.406360  0.205399   
136741  81847  -0.418805   0.740210 -0.340755 -0.849297  2.720622  3.617123   

              V7        V8        V9  ...       V21       V22       V23  \
0       0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474   
1      -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288   
2       0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412   
3       0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321   
4       0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458   
...          ...       ...       ...  ...       ...       ...       ...   
136737 -1.678594 -0.472964  1.746022  ... -1.950947  1.310955  3.551754   
136738 -1.553317  0.090583 -0.915535  ... -0.275377 -0.339339 -0.071301   
136739  0.255298 -0.118738 -0.350417  ...  0.113590  0.182403 -0.230636   
136740 -0.314283  0.605285  0.109673  ... -0.001167  0.019274 -0.191846   
136741  0.524513  0.658118  0.207301  ... -0.160854 -0.264370 -0.207264   

             V24       V25       V26       V27                 V28  Amount  \
0       0.066928  0.128539 -0.189115  0.133558           -0.021053  149.62   
1      -0.339846  0.167170  0.125895 -0.008983            0.014724    2.69   
2      -0.689281 -0.327642 -0.139097 -0.055353           -0.059752  378.66   
3      -1.175575  0.647376 -0.221929  0.062723            0.061458  123.50   
4       0.141267 -0.206010  0.502292  0.219422            0.215153   69.99   
...          ...       ...       ...       ...                 ...     ...   
136737  0.384646  1.611309  1.441667  2.522778   -1.41864956210692  117.02   
136738 -0.464163  0.329077 -0.146875  0.066696  0.0310399021239038   58.00   
136739  0.035431  0.690598 -0.336135 -0.002191  0.0222817106909724   85.90   
136740 -0.389853 -0.148594  0.426455 -0.013927  0.0384589819489235    6.80   
136741  0.987706  0.237498 -0.580972 -0.119332                   -     NaN   

        Class  
0         0.0  
1         0.0  
2         0.0  
3         0.0  
4         0.0  
...       ...  
136737    0.0  
136738    0.0  
136739    0.0  
136740    0.0  
136741    NaN  

[136742 rows x 31 columns]

In [58]:
# prompt: convert my df data set into tensor

df_tensor = torch.tensor(df.values)

df_tensor

TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, complex64, complex128, int64, int32, int16, int8, uint64, uint32, uint16, uint8, and bool.

In [59]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 136742 entries, 0 to 136741
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   Time    136742 non-null  int64  
 1   V1      136742 non-null  float64
 2   V2      136742 non-null  float64
 3   V3      136742 non-null  float64
 4   V4      136742 non-null  float64
 5   V5      136742 non-null  float64
 6   V6      136742 non-null  float64
 7   V7      136742 non-null  float64
 8   V8      136742 non-null  float64
 9   V9      136742 non-null  float64
 10  V10     136742 non-null  float64
 11  V11     136742 non-null  float64
 12  V12     136742 non-null  float64
 13  V13     136742 non-null  float64
 14  V14     136742 non-null  float64
 15  V15     136742 non-null  float64
 16  V16     136742 non-null  float64
 17  V17     136742 non-null  float64
 18  V18     136742 non-null  float64
 19  V19     136742 non-null  float64
 20  V20     136742 non-null  float64
 21  V21     13

In [ ]:
# prompt: convert df into float



In [ ]:
df_tensor.shape

In [60]:
# inputs=df.drop('Class',axis=1)
# target=df['Class']

inputs = df_tensor[:,:-1]
targets = df_tensor[:,-1]

In [61]:

inputs = inputs.type(torch.float32)

inputs.shape

torch.Size([9965, 30])

In [62]:
from torch.utils.data import TensorDataset
train_ds = TensorDataset(inputs, targets)
train_ds[0:3]

(tensor([[ 0.0000e+00, -1.3598e+00, -7.2781e-02,  2.5363e+00,  1.3782e+00,
          -3.3832e-01,  4.6239e-01,  2.3960e-01,  9.8698e-02,  3.6379e-01,
           9.0794e-02, -5.5160e-01, -6.1780e-01, -9.9139e-01, -3.1117e-01,
           1.4682e+00, -4.7040e-01,  2.0797e-01,  2.5791e-02,  4.0399e-01,
           2.5141e-01, -1.8307e-02,  2.7784e-01, -1.1047e-01,  6.6928e-02,
           1.2854e-01, -1.8911e-01,  1.3356e-01, -2.1053e-02,  1.4962e+02],
         [ 0.0000e+00,  1.1919e+00,  2.6615e-01,  1.6648e-01,  4.4815e-01,
           6.0018e-02, -8.2361e-02, -7.8803e-02,  8.5102e-02, -2.5543e-01,
          -1.6697e-01,  1.6127e+00,  1.0652e+00,  4.8910e-01, -1.4377e-01,
           6.3556e-01,  4.6392e-01, -1.1480e-01, -1.8336e-01, -1.4578e-01,
          -6.9083e-02, -2.2578e-01, -6.3867e-01,  1.0129e-01, -3.3985e-01,
           1.6717e-01,  1.2589e-01, -8.9831e-03,  1.4724e-02,  2.6900e+00],
         [ 1.0000e+00, -1.3584e+00, -1.3402e+00,  1.7732e+00,  3.7978e-01,
          -5.0320e-01, 

In [63]:
from torch.utils.data import DataLoader
bs=10
train_loader = DataLoader(train_ds, batch_size = bs, shuffle = True)

In [64]:
for xb, yb in train_loader:
    print(xb)
    print(yb)
    break

tensor([[ 3.1720e+03, -1.2591e+00, -5.6572e-01,  2.6011e+00,  3.5985e+00,
         -1.4930e+00,  1.6833e+00,  6.9979e-01,  1.2426e-01,  2.7751e-01,
          4.4368e-01, -1.1162e+00, -8.4942e-01, -1.7135e+00, -7.8257e-01,
         -4.5166e-01, -9.9818e-01,  1.0162e+00, -2.1226e-01,  7.9460e-01,
          1.3363e-01,  1.1902e-01,  8.8761e-01,  2.7845e-01,  4.2508e-01,
         -2.5533e-01,  4.1634e-01,  1.8900e-02, -6.6565e-02,  3.3996e+02],
        [ 1.3485e+04, -5.2152e-01,  6.3426e-01,  2.5967e+00,  1.2386e+00,
          3.0855e-02,  9.9851e-02,  3.7820e-01, -9.5721e-02,  1.6226e+00,
         -8.6556e-01,  5.1178e-01, -1.9372e+00,  1.4861e+00,  7.3791e-01,
         -1.7228e+00, -1.2326e+00,  1.2646e+00, -6.5572e-01, -4.7254e-01,
         -7.8610e-02, -1.3062e-01,  3.6340e-01, -1.3780e-01,  5.7145e-01,
         -1.7652e-01, -4.3332e-01, -1.7032e-03, -8.2008e-02,  9.0000e+00],
        [ 7.3310e+03,  1.4569e-01,  6.4863e-02,  1.5081e+00, -6.6177e-01,
         -2.2749e-01, -1.8615e-01,  

In [65]:
class Logistic_Regression(torch.nn.Module):
     def __init__(self, input_dim, output_dim):
         super(Logistic_Regression, self).__init__()
         self.linear = torch.nn.Linear(input_dim, output_dim,dtype=torch.float32)
     def forward(self, x):
         outputs = torch.sigmoid(self.linear(x))
         return outputs

In [66]:
model = Logistic_Regression(30,1)

In [67]:
model

Logistic_Regression(
  (linear): Linear(in_features=30, out_features=1, bias=True)
)

In [68]:
# prompt: convert my inputs into float 64

inputs = inputs.type(torch.float32)

inputs.shape

torch.Size([9965, 30])

In [69]:
preds = model(inputs)

In [70]:
preds

tensor([[1.0000],
        [0.6051],
        [1.0000],
        ...,
        [1.0000],
        [1.0000],
        [   nan]], grad_fn=<SigmoidBackward0>)

In [71]:
def class_loss(predictions, targets):
    return torch.where(targets==preds, 1., 0).mean()
  # return torch.where(targets==pred, 0, 1).mean()

In [72]:
loss = class_loss(preds, targets)
loss

tensor(0.0030)

In [73]:
model.parameters()

<generator object Module.parameters at 0x7dd75b389700>

In [74]:
opt = torch.optim.SGD(model.parameters(), lr=1e-5)

In [75]:
list(model.parameters())


[Parameter containing:
 tensor([[ 0.0069,  0.1792, -0.1531,  0.0692, -0.0822,  0.0029,  0.1357,  0.0960,
           0.1438, -0.0036,  0.1717, -0.0840,  0.1090, -0.0428,  0.1444, -0.0486,
           0.0254,  0.1400,  0.1411, -0.0663,  0.1569,  0.0156, -0.0155,  0.1011,
          -0.0116,  0.1028,  0.0171,  0.0723, -0.1308,  0.1038]],
        requires_grad=True),
 Parameter containing:
 tensor([0.1200], requires_grad=True)]

In [84]:
def fit(num_epochs, model, loss_fn, opt, train_dl):
    # correct = 0
    total = 0
    correct = 0
    # Repeat for given number of epochs
    for epoch in range(num_epochs):
        epoch_loss = 0
        epoch_acc = 0
        # Train with batches of data
        for xb,yb in train_dl:


            # 1. Generate predictions
            pred = model(xb)

            # loss=loss.requires
            # 2. Calculate loss
            loss = loss_fn(pred, yb)

            y_pred_tag = torch.round(pred)
            correct_results_sum = (y_pred_tag == yb).sum().float()
            acc = correct_results_sum/yb.shape[0]
            acc = torch.round(acc * 100)
            loss.requires_grad = True
            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Reset the gradients to zero
            opt.zero_grad()

            epoch_loss += loss.item()

        # Print the progress
        if (epoch+1) % 10 == 0:

            print('Epoch [{}/{}], Loss: {:.4f}, Accuracy: {:.2f}'.format(epoch+1, num_epochs, loss.item(), acc/len(train_dl)))

In [86]:
preds = model(inputs)
preds

tensor([[1.0000],
        [0.6051],
        [1.0000],
        ...,
        [1.0000],
        [1.0000],
        [   nan]], grad_fn=<SigmoidBackward0>)

In [85]:
fit(100, model, class_loss, opt, train_loader)

Epoch [10/100], Loss: 0.0000, Accuracy: 0.00
Epoch [20/100], Loss: 0.0000, Accuracy: 0.00
Epoch [30/100], Loss: 0.0000, Accuracy: 0.00
Epoch [40/100], Loss: 0.0000, Accuracy: 0.00
Epoch [50/100], Loss: 0.0000, Accuracy: 0.00
Epoch [60/100], Loss: 0.0000, Accuracy: 0.00
Epoch [70/100], Loss: 0.1566, Accuracy: 0.10
Epoch [80/100], Loss: 0.0000, Accuracy: 0.00
Epoch [90/100], Loss: 0.0000, Accuracy: 0.00
Epoch [100/100], Loss: 0.0000, Accuracy: 0.00
